#!/usr/bin/env node
/**
 * manage_effect Tool Integration Tests
 * Covers all 58 actions with real optional-parameter coverage.
 */

import { runToolTests } from '../../test-runner.mjs';

const TEST_FOLDER = '/Game/MCPTest/AuthoringAssets';
const ts = Date.now();
const TEST_ACTOR = `TestActor_${ts}`;
const EFFECT_ACTOR = `TestEffectActor_${ts}`;
const SPAWNED_EFFECT_ACTOR = `TestSpawnedEffectActor_${ts}`;
const SYSTEM_NAME = `Testniagara_system_${ts}`;
const EMITTER_ASSET_NAME = `Testniagara_emitter_${ts}`;
const SYSTEM_PATH = `${TEST_FOLDER}/${SYSTEM_NAME}.${SYSTEM_NAME}`;
const EMITTER_PATH = `${TEST_FOLDER}/${EMITTER_ASSET_NAME}.${EMITTER_ASSET_NAME}`;
const DEFAULT_EMITTER = 'DefaultEmitter';
const USER_PARAM = `MCPUserParam_${ts}`;
const BOUND_PARAM = `MCPBoundParam_${ts}`;
const EVENT_NAME = `MCPEvent_${ts}`;
const STAGE_NAME = `MCPStage_${ts}`;
const BASIC_MATERIAL = '/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial';
const CUBE_MESH = '/Engine/BasicShapes/Cube.Cube';

const testCases = [
  // === SETUP ===
  { scenario: 'Setup: create test folder', toolName: 'manage_asset', arguments: { action: 'create_folder', path: TEST_FOLDER }, expected: 'success|already exists' },
  { scenario: 'Setup: spawn test actor', toolName: 'control_actor', arguments: { action: 'spawn', classPath: '/Engine/BasicShapes/Cube', actorName: TEST_ACTOR, location: { x: 0, y: 0, z: 100 } }, expected: 'success' },

  // === CREATE ===
  { scenario: 'CREATE: create_niagara_system', toolName: 'manage_effect', arguments: { action: 'create_niagara_system', name: SYSTEM_NAME, path: TEST_FOLDER, savePath: TEST_FOLDER }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_niagara_emitter', toolName: 'manage_effect', arguments: { action: 'create_niagara_emitter', name: EMITTER_ASSET_NAME, path: TEST_FOLDER, savePath: TEST_FOLDER, emitterName: EMITTER_ASSET_NAME }, expected: 'success|already exists' },

  // === ACTION ===
  { scenario: 'ACTION: particle with preset and debug options', toolName: 'manage_effect', arguments: { action: 'particle', preset: 'Default', location: { x: 0, y: 0, z: 100 }, shapeType: 'sphere', radius: 30, color: [255, 64, 32, 255], duration: 0.1, timeoutMs: 30000 }, expected: 'success', assertions: [{ path: 'structuredContent.result.shapeType', equals: 'sphere', label: 'particle preset path drew requested debug shape' }] },
  { scenario: 'ACTION: niagara with actor attachment', toolName: 'manage_effect', arguments: { action: 'niagara', systemPath: SYSTEM_PATH, actorName: EFFECT_ACTOR, attachToActor: TEST_ACTOR, location: { x: 0, y: 0, z: 120 } }, expected: 'success' },
  { scenario: 'ACTION: debug_shape alias shape', toolName: 'manage_effect', arguments: { action: 'debug_shape', shape: 'box', location: { x: 20, y: 0, z: 100 }, radius: 25, color: [0, 128, 255, 255], duration: 0.1 }, expected: 'success', assertions: [{ path: 'structuredContent.result.shapeType', equals: 'box', label: 'shape alias reached native shapeType' }] },
  { scenario: 'CREATE: spawn_niagara with system alias', toolName: 'manage_effect', arguments: { action: 'spawn_niagara', system: SYSTEM_PATH, actorName: SPAWNED_EFFECT_ACTOR, location: { x: 40, y: 0, z: 120 } }, expected: 'success' },
  { scenario: 'CREATE: create_dynamic_light with light properties', toolName: 'manage_effect', arguments: { action: 'create_dynamic_light', name: `Testdynamic_light_${ts}`, location: { x: 80, y: 0, z: 250 }, lightType: 'Point', intensity: 750, color: [1, 0.8, 0.4, 1] }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_volumetric_fog with fog properties', toolName: 'manage_effect', arguments: { action: 'create_volumetric_fog', name: `Testvolumetric_fog_${ts}`, density: 0.02, scattering: 0.6, extinction: 0.4 }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_particle_trail', toolName: 'manage_effect', arguments: { action: 'create_particle_trail', name: `Testparticle_trail_${ts}`, systemPath: SYSTEM_PATH, location: { x: 120, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_environment_effect', toolName: 'manage_effect', arguments: { action: 'create_environment_effect', name: `Testenvironment_effect_${ts}`, systemPath: SYSTEM_PATH, location: { x: 160, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_impact_effect', toolName: 'manage_effect', arguments: { action: 'create_impact_effect', name: `Testimpact_effect_${ts}`, systemPath: SYSTEM_PATH, location: { x: 200, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_niagara_ribbon', toolName: 'manage_effect', arguments: { action: 'create_niagara_ribbon', name: `Testniagara_ribbon_${ts}`, systemPath: SYSTEM_PATH, location: { x: 240, y: 0, z: 120 } }, expected: 'success|already exists' },

  // === PLAYBACK ===
  { scenario: 'ACTION: activate', toolName: 'manage_effect', arguments: { action: 'activate', actorName: EFFECT_ACTOR, reset: false }, expected: 'success' },
  { scenario: 'ACTION: activate_effect by systemName', toolName: 'manage_effect', arguments: { action: 'activate_effect', systemName: EFFECT_ACTOR }, expected: 'success' },
  { scenario: 'ACTION: deactivate', toolName: 'manage_effect', arguments: { action: 'deactivate', actorName: EFFECT_ACTOR }, expected: 'success' },
  { scenario: 'ACTION: reset', toolName: 'manage_effect', arguments: { action: 'reset', actorName: EFFECT_ACTOR, reset: true }, expected: 'success' },
  { scenario: 'PLAYBACK: advance_simulation', toolName: 'manage_effect', arguments: { action: 'advance_simulation', actorName: EFFECT_ACTOR, deltaTime: 0.016, steps: 2 }, expected: 'success', assertions: [{ path: 'structuredContent.result.steps', equals: 2, label: 'native simulation step count applied' }] },

  // === GRAPH ===
  { scenario: 'ADD: add_niagara_module', toolName: 'manage_effect', arguments: { action: 'add_niagara_module', assetPath: SYSTEM_PATH, systemPath: SYSTEM_PATH, modulePath: '/Niagara/Modules/Emitter/EmitterState.EmitterState', scriptType: 'Spawn', name: 'Testniagara_module' }, expected: 'success|already exists', captureResult: { key: 'niagaraModuleNodeId', fromField: 'result.nodeId' } },
  { scenario: 'CONNECT: connect_niagara_pins', toolName: 'manage_effect', arguments: { action: 'connect_niagara_pins', assetPath: SYSTEM_PATH, autoConnect: true }, expected: 'success', assertions: [{ path: 'structuredContent.result.connected', equals: true, label: 'real Niagara graph pins connected' }, { path: 'structuredContent.result.autoConnected', equals: true, label: 'native auto-connect path executed' }] },
  { scenario: 'DELETE: remove_niagara_node', toolName: 'manage_effect', arguments: { action: 'remove_niagara_node', assetPath: SYSTEM_PATH, nodeId: '${captured:niagaraModuleNodeId}' }, expected: 'success', assertions: [{ path: 'structuredContent.result.removed', equals: true, label: 'captured Niagara graph node removed' }] },

  // === RUNTIME PARAMETER ===
  { scenario: 'CONFIG: set_niagara_parameter', toolName: 'manage_effect', arguments: { action: 'set_niagara_parameter', actorName: EFFECT_ACTOR, parameterName: 'MCPParameter', parameterType: 'Float', value: 1.25 }, expected: 'success', assertions: [{ path: 'structuredContent.result.applied', equals: true, label: 'runtime Niagara parameter value applied' }] },
  { scenario: 'DELETE: clear_debug_shapes', toolName: 'manage_effect', arguments: { action: 'clear_debug_shapes' }, expected: 'success|not found' },
  { scenario: 'ACTION: cleanup with explicit filter', toolName: 'manage_effect', arguments: { action: 'cleanup', filter: `NoSuchManageEffectActor_${ts}` }, expected: 'success|not found' },
  { scenario: 'INFO: list_debug_shapes', toolName: 'manage_effect', arguments: { action: 'list_debug_shapes' }, expected: 'success' },

  // === NIAGARA AUTHORING ===
  { scenario: 'ADD: add_emitter_to_system', toolName: 'manage_effect', arguments: { action: 'add_emitter_to_system', systemPath: SYSTEM_PATH, emitterPath: EMITTER_PATH, save: false }, expected: 'success|already exists' },
  { scenario: 'CONFIG: set_emitter_properties', toolName: 'manage_effect', arguments: { action: 'set_emitter_properties', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, emitterProperties: { enabled: true }, save: false }, expected: 'success' },
  { scenario: 'ADD: add_spawn_rate_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_rate_module', systemPath: SYSTEM_PATH, emitter: DEFAULT_EMITTER, spawnRate: 123, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.spawnRate', equals: 123, label: 'spawnRate applied to native module' }] },
  { scenario: 'ADD: add_spawn_burst_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_burst_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, burstCount: 7, burstTime: 0.25, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.burstCount', equals: 7, label: 'burstCount reached native module' }, { path: 'structuredContent.result.burstTime', equals: 0.25, label: 'burstTime reached native module' }] },
  { scenario: 'ADD: add_spawn_per_unit_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_per_unit_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, spawnPerUnit: 2.5, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.spawnPerUnit', equals: 2.5, label: 'spawnPerUnit reached native module' }] },
  { scenario: 'ADD: add_initialize_particle_module', toolName: 'manage_effect', arguments: { action: 'add_initialize_particle_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, lifetime: 3, mass: 1.5, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.lifetime', equals: 3, label: 'lifetime reached native module' }, { path: 'structuredContent.result.mass', equals: 1.5, label: 'mass reached native module' }] },
  { scenario: 'ADD: add_particle_state_module', toolName: 'manage_effect', arguments: { action: 'add_particle_state_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_force_module', toolName: 'manage_effect', arguments: { action: 'add_force_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, forceType: 'Gravity', forceStrength: 456, forceVector: { x: 0, y: 0, z: -456 }, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.forceType', equals: 'Gravity', label: 'forceType reached native module' }, { path: 'structuredContent.result.forceStrength', equals: 456, label: 'forceStrength reached native module' }] },
  { scenario: 'ADD: add_velocity_module', toolName: 'manage_effect', arguments: { action: 'add_velocity_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, velocity: { x: 1, y: 2, z: 3 }, velocityMode: 'Linear', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.velocityMode', equals: 'Linear', label: 'velocityMode reached native module' }] },
  { scenario: 'ADD: add_acceleration_module', toolName: 'manage_effect', arguments: { action: 'add_acceleration_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, acceleration: { x: 0, y: 0, z: -980 }, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.parameterAdded', equals: true, label: 'acceleration parameter added to Niagara system' }] },
  { scenario: 'ADD: add_size_module', toolName: 'manage_effect', arguments: { action: 'add_size_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, sizeMode: 'Uniform', uniformSize: 12, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.parameterAdded', equals: true, label: 'size parameter added to Niagara system' }, { path: 'structuredContent.result.uniformSize', equals: 12, label: 'uniformSize reached native module' }] },
  { scenario: 'ADD: add_color_module', toolName: 'manage_effect', arguments: { action: 'add_color_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, color: { r: 1, g: 0.5, b: 0.25, a: 1 }, colorMode: 'Direct', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.parameterAdded', equals: true, label: 'color parameter added to Niagara system' }, { path: 'structuredContent.result.colorMode', equals: 'Direct', label: 'colorMode reached native module' }] },
  { scenario: 'ADD: add_sprite_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_sprite_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, materialPath: BASIC_MATERIAL, alignment: 'Unaligned', facingMode: 'FaceCamera', save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_mesh_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_mesh_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, meshPath: CUBE_MESH, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_ribbon_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_ribbon_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, materialPath: BASIC_MATERIAL, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_light_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_light_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, lightRadius: 200, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_collision_module', toolName: 'manage_effect', arguments: { action: 'add_collision_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, collisionMode: 'SceneDepth', restitution: 0.4, friction: 0.1, dieOnCollision: true, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'collision module added to Niagara stack' }, { path: 'structuredContent.result.parameterAdded', equals: true, label: 'collision parameters added to Niagara system' }, { path: 'structuredContent.result.dieOnCollision', equals: true, label: 'dieOnCollision reached native module' }] },
  { scenario: 'ADD: add_kill_particles_module', toolName: 'manage_effect', arguments: { action: 'add_kill_particles_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, killCondition: 'Age', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'kill particles module added to Niagara stack' }, { path: 'structuredContent.result.killCondition', equals: 'Age', label: 'killCondition reached native module' }] },
  { scenario: 'ADD: add_camera_offset_module', toolName: 'manage_effect', arguments: { action: 'add_camera_offset_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, cameraOffset: 4, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'camera offset module added to Niagara stack' }, { path: 'structuredContent.result.parameterAdded', equals: true, label: 'camera offset parameter added to Niagara system' }, { path: 'structuredContent.result.cameraOffset', equals: 4, label: 'cameraOffset reached native module' }] },
  { scenario: 'ADD: add_user_parameter', toolName: 'manage_effect', arguments: { action: 'add_user_parameter', systemPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterType: 'Float', save: false }, expected: 'success|already exists' },
  { scenario: 'CONFIG: set_parameter_value', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterValue: 2.5, save: false }, expected: 'success' },
  { scenario: 'CONNECT: bind_parameter_to_source applies real assignment binding', toolName: 'manage_effect', arguments: { action: 'bind_parameter_to_source', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: BOUND_PARAM, parameterType: 'Float', sourceBinding: 'Emitter.Age', save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.bindingApplied', equals: true, label: 'real Niagara parameter binding applied' }, { path: 'structuredContent.result.assignmentModuleAdded', equals: true, label: 'assignment module added to Niagara stack' }, { path: 'structuredContent.result.niagaraDefaultSource', equals: 'Emitter Age', label: 'Emitter.Age normalized to Niagara engine constant' }] },
  { scenario: 'ADD: add_skeletal_mesh_data_interface', toolName: 'manage_effect', arguments: { action: 'add_skeletal_mesh_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPSkelDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'skeletal mesh data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_static_mesh_data_interface', toolName: 'manage_effect', arguments: { action: 'add_static_mesh_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPStaticDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'static mesh data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_spline_data_interface', toolName: 'manage_effect', arguments: { action: 'add_spline_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPSplineDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'spline data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_audio_spectrum_data_interface', toolName: 'manage_effect', arguments: { action: 'add_audio_spectrum_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPAudioDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'audio spectrum data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_collision_query_data_interface', toolName: 'manage_effect', arguments: { action: 'add_collision_query_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPCollisionDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'collision query data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_event_generator', toolName: 'manage_effect', arguments: { action: 'add_event_generator', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, eventName: EVENT_NAME, eventType: 'Location', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.eventGeneratorAdded', equals: true, label: 'event generator mutation recorded' }] },
  { scenario: 'ADD: add_event_receiver', toolName: 'manage_effect', arguments: { action: 'add_event_receiver', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, eventName: EVENT_NAME, spawnOnEvent: true, eventSpawnCount: 2, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.eventHandlerAdded', equals: true, label: 'event handler added to Niagara emitter' }, { path: 'structuredContent.result.eventGraphCreated', equals: true, label: 'event handler output graph created' }, { path: 'structuredContent.result.spawnOnEvent', equals: true, label: 'spawnOnEvent reached native event receiver' }] },
  { scenario: 'CONFIG: configure_event_payload', toolName: 'manage_effect', arguments: { action: 'configure_event_payload', systemPath: SYSTEM_PATH, eventName: EVENT_NAME, eventPayload: [{ name: 'PayloadFloat', type: 'Float' }], save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.eventPayloadConfigured', equals: true, label: 'event payload parameters added' }, { path: 'structuredContent.result.payloadAttributeCount', equals: 1, label: 'eventPayload attributes reached native payload configuration' }] },
  { scenario: 'TOGGLE: enable_gpu_simulation', toolName: 'manage_effect', arguments: { action: 'enable_gpu_simulation', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, fixedBoundsEnabled: true, deterministicEnabled: true, save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.fixedBoundsEnabled', equals: true, label: 'fixedBoundsEnabled reached native GPU configuration' }, { path: 'structuredContent.result.deterministicEnabled', equals: true, label: 'deterministicEnabled reached native GPU configuration' }] },
  { scenario: 'ADD: add_simulation_stage', toolName: 'manage_effect', arguments: { action: 'add_simulation_stage', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, stageName: STAGE_NAME, stageIterationSource: 'Particles', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.simulationStageAdded', equals: true, label: 'simulation stage added to Niagara emitter' }, { path: 'structuredContent.result.simulationStageGraphCreated', equals: true, label: 'simulation stage output graph created' }, { path: 'structuredContent.result.iterationSource', equals: 'Particles', label: 'stageIterationSource reached native stage configuration' }] },
  { scenario: 'INFO: get_niagara_info', toolName: 'manage_effect', arguments: { action: 'get_niagara_info', assetPath: SYSTEM_PATH }, expected: 'success' },
  { scenario: 'ACTION: validate_niagara_system', toolName: 'manage_effect', arguments: { action: 'validate_niagara_system', system: SYSTEM_PATH }, expected: 'success' },

  // === CLEANUP ===
  { scenario: 'Cleanup: delete spawned Niagara actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: SPAWNED_EFFECT_ACTOR }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete primary Niagara actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: EFFECT_ACTOR }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete test actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: TEST_ACTOR }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete test folder', toolName: 'manage_asset', arguments: { action: 'delete', path: TEST_FOLDER, force: true }, expected: 'success|not found' },
];

runToolTests('manage-effect', testCases);
